---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: server_group_one
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: server_group_two
  become: true
  tasks:

  - name: install mariadb package
    tags: mariadb, ubuntu
    package:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
