---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: server_group_two
  become: true
  tasks:

  - name: copy default site html file
    tags: html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
